name: Deploy to Raspberry Pi via ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -p 14212 pi@tcp://2.tcp.eu.ngrok.io << 'EOF'
            docker stop shooting-front || true
            docker rm shooting-front || true
            cd /home/pi/shooting-front
            git pull
            docker build -t shooting-front .
            docker run -d -p 3000:3000 --name shooting-front --restart unless-stopped shooting-front
          EOF
        env:
          SSH_USERNAME: pi
          SSH_HOST: <NGROK_ADDRESS>
          NGROK_PORT: <NGROK_PORT>
